[package]
name = "kern-context"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kern-types.workspace = true
kern-repo.workspace = true
kern-capability.workspace = true
syn = { version = "2", default-features = false, features = ["full", "parsing", "printing", "visit"] }
proc-macro2 = { version = "1", default-features = false, features = ["span-locations"] }

[lints]
workspace = true
